name: CI

on:
  - pull_request
  - push

jobs:
  Lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: install
        run: npm ci
      - name: XO
        run: npx xo

  Test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: install
        run: npm ci
      - name: build
        run: npm run build
      - name: AVA
        run: npx ava

  Build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: install
        run: npm ci
      - name: build
        run: npm run build

  Types:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: install
        run: npm ci
      - run: npm run build
      - run: npx tsd
